books/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.home, name='home'),
    path('book_register/', views.book_register, name='book_register'),
    path('book_details/<int:id>/', views.book_details, name='book_details'),
    path('book_edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('book_delete/<int:book_id>/', views.delete_book, name='book_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books_online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from authors.models import Author
from PIL import Image
import os

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.DO_NOTHING)
    year = models.CharField(max_length=4)
    genre = models.CharField(max_length=50)
    cover_image = models.ImageField(upload_to='book_covers/', blank=True, null=True)
    synopsis = models.TextField(null=True, blank=True)



    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # salva a imagem original

        if self.cover_image:
            img_path = self.cover_image.path
            img = Image.open(img_path)

            # Define o tamanho máximo para a miniatura
            max_size = (200, 250)  
            img.thumbnail(max_size)  # Redimensiona mantendo a proporção
            
            img.save(img_path, format="JPEG", quality=80)  # Salva a imagem otimizada

    def __str__(self):
        return self.title

books/forms.py
from datetime import datetime
from django import forms
from .models import Book, Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'year', 'genre', 'cover_image', 'synopsis']
        labels = {
            'title': 'Título',
            'author': 'Autor',
            'year': 'Publicação',
            'genre': 'Gênero',
            'cover_image': 'Capa do Livro',
            'synopsis': 'Sinopse'
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Título'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'year': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ano de Publicação'}),
            'genre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Gênero'}),
            'cover_image': forms.FileInput(attrs={'class': 'form-control'}),
            'synopsis': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Sinopse'})
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all().order_by('first_name')

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if title.strip() == '':
            raise forms.ValidationError('O título não pode ser vazio ou somente espaços em branco')
        return title
    
    def clean_genre(self):
        genre = self.cleaned_data.get('genre')
        if any(char.isdigit() for char in genre):
            raise forms.ValidationError('O gênero não pode conter números')
        if genre.strip() == '':
            raise forms.ValidationError('O gênero não pode ser vazio ou somente espaços em branco')
        return genre
    
    def clean_year(self):
        actual_year = datetime.now().year
        year = self.cleaned_data.get('year')
        if year.strip() == '':
            raise forms.ValidationError('O ano de publicação não pode ser vazio ou somente espaços em branco')
        if not year.isdigit():
            raise forms.ValidationError('O ano de publicação deve conter somente números')
        if int(year) > actual_year:
            raise forms.ValidationError('O ano de publicação não pode ser maior que o ano atual')
        return year

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Book
from .forms import BookForm
from authors.models import Author


def home(request):
    books = Book.objects.all().order_by('title')
    authors = Author.objects.all().order_by('first_name')
    return render(request, 'home.html', {'books': books, 'authors': authors})


def book_register(request):
    books = Book.objects.all()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Livro cadastrado com sucesso!')
            return redirect("/")
    else:
        form = BookForm()

    return render(request, "book_register.html", {"form": form, "books": books})


def book_details(request, id):
    book = Book.objects.get(id=id)
    authors = Author.objects.all().order_by('first_name')
    return render(request, "book_details.html", {"book": book, "authors": authors})


def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            if 'cover_image-clear' in request.POST:
                book.cover_image.delete()
            form.save()
            messages.success(request, 'Livro editado com sucesso!')
            return redirect(f'/book_details/{book_id}/')
    else:
        form = BookForm(instance=book)
    authors = Author.objects.all()
    return render(request, 'book_details.html', {'form': form, 'book': book, 'authors': authors})


def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == 'POST':
        book.delete()
        messages.success(request, 'Livro deletado com sucesso!')
        return redirect('/')
    return render(request, 'book_details.html', {'book': book})

books/templates/book_details.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}
<div class="container mt-4 d-flex justify-content-center">
    <div class="card mb-4" style="max-width: 800px; width: 100%;">
        <div class="row g-0">
            <div class="col-md-8 p-3">
                <h2>{{ book.title }}</h2>
                <p><strong>Autor:</strong> {{ book.author }}</p>
                <p><strong>Gênero:</strong> {{ book.genre }}</p>
                <p><strong>Ano de publicação:</strong> {{ book.year }}</p>
                
                <div class="mt-3">
                    <button type="button" class="btn btn-primary btn-edit-book"
                            data-book-id="{{ book.id }}"
                            data-book-title="{{ book.title }}"
                            data-book-author="{{ book.author.id }}"
                            data-book-year="{{ book.year }}"
                            data-book-genre="{{ book.genre }}"
                            data-book-synopsis="{{ book.synopsis }}"
                            data-book-cover-url="{% if book.cover_image %}{{ book.cover_image.url }}{% else %}https://dummyimage.com/150x200/9e9e9e/030303.png&text=+SEM+CAPA{% endif %}">
                        Editar
                    </button>
                    <button type="button" class="btn btn-danger btn-delete"
                            data-book-id="{{ book.id }}"
                            data-book-title="{{ book.title }}"
                            data-book-cover-url="{% if book.cover_image %}{{ book.cover_image.url }}{% else %}https://dummyimage.com/200x250/9e9e9e/030303.png&text=+SEM+CAPA{% endif %}">
                        Deletar
                    </button>
                </div>
            </div>
            {% if book.cover_image %}
                <div class="col-md-4 p-3">
                    <img src="{{ book.cover_image.url }}" class="img-fluid" alt="Capa de {{ book.title }}" style="height: 100%; object-fit: cover;">
                </div>
            {% else %}
                <div class="col-md-4 p-3">
                    <img src="https://dummyimage.com/200x250/9e9e9e/030303.png&text=+SEM+CAPA" class="img-fluid" alt="Capa de {{ book.title }}" style="height: 100%; object-fit: cover;">
                </div>
            {% endif %}
        </div>

        <!-- Sinopse abaixo de tudo -->
        <div class="container row mt-4">
            <div class="col-md-12 p-3">
                <h3>Sinopse</h3>
                <p>{{ book.synopsis }}</p>
            </div>
        </div>
    </div>
</div>

{% include "edit_modal_book.html" %}
{% include "delete_modal_book.html" %}

<script src="{% static 'js/edit_book.js' %}"></script>
<script src="{% static 'js/delete_book.js' %}"></script>

{% endblock %}

books/templates/book_register.html
{% extends "base_generic.html" %}

{% block content %}

<h2 class="text-center">Cadastro de Livros</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4 mb-3">
            <label for="book_title" class="form-label">Título</label>
            {{ form.title }}
            {% if form.title.errors %}
                <div class="text-danger">
                    {{ form.title.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_author" class="form-label">Autor</label>
            {{ form.author }}
            {% if form.author.errors %}
                <div class="text-danger">
                    {{ form.author.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_genre" class="form-label">Gênero Literário</label>
            {{ form.genre }}
            {% if form.genre.errors %}
                <div class="text-danger">
                    {{ form.genre.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 mb-3">
            <label for="book_year" class="form-label">Ano de publicação</label>
            {{ form.year }}
            {% if form.year.errors %}
                <div class="text-danger">
                    {{ form.year.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-4 mb-3">
            <label for="book_cover" class="form-label">Capa do livro</label>
            {{ form.cover_image }}
            {% if form.cover_image.errors %}
                <div class="text-danger">
                    {{ form.cover_image.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="mb-3">
        <label for="book_synopsis" class="form-label">Sinopse</label>
        {{ form.synopsis }}
        {% if form.synopsis.errors %}
            <div class="text-danger">
                {{ form.synopsis.errors }}
            </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>
{% endblock content %}

books/templates/delete_modal_book.html
<div class="modal fade" id="deleteBookModal" tabindex="-1" aria-labelledby="deleteBookModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteBookModalLabel">Deseja realmente deletar o livro <i id="deleteBookName"></i>?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <img id="deleteBookPhoto" src="" alt="Capa do Livro" class="img-fluid mb-3" style="width: 200px; height: 250px;">
                
                <form id="deleteBookForm" method="post" action="{% url 'books:book_delete' book_id=book.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" id="deleteBookId">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

books/templates/edit_modal_book.html
<div class="modal fade" id="editBookModal" tabindex="-1" aria-labelledby="editBookModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editBookModalLabel">Editar Livro</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editBookForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3 text-center d-flex align-items-end gap-2" style="justify-content: center;">
                        <div style="position: relative; display: inline-block;">
                            <img id="bookCover" src="" alt="Capa do Livro" title="Alterar imagem" 
                                 class="img-thumbnail" style="width: 150px; height: 200px; cursor: pointer;">
                            <input type="file" class="form-control" id="editCover" name="cover_image" style="display: none;">
                            <input type="checkbox" name="cover_image-clear" id="cover_image-clear" style="display: none;">
                            <!-- Ícone da câmera -->
                            <i class="fas fa-camera position-absolute text-white bg-dark rounded-circle p-1"
                               style="bottom: 5px; left: 50%; transform: translateX(-50%); font-size: 16px; opacity: 0.7;">
                            </i>
                        </div>
                        
                        <button type="button" class="btn btn-danger btn-sm" id="deleteCoverButton" title="Deletar Capa">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" id="editTitle" name="title" required>
                                <label for="editTitle">Título</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating mb-3">
                                <select class="form-control" id="editAuthor" name="author" required>
                                    {% for author in authors %}
                                        <option value="{{ author.id }}">{{ author }}</option>
                                    {% endfor %}
                                </select>
                                <label for="editAuthor">Autor</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="editYear" name="year" required>
                        <label for="editYear">Ano de publicação</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="editGenre" name="genre" required>
                        <label for="editGenre">Gênero Literário</label>
                    </div>
                    <div class="form-floating mb-3">
                        <textarea class="form-control" id="editSynopsis" name="synopsis" required></textarea>
                        <label for="editSynopsis">Sinopse</label>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

books/templates/home.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

<div class="container mt-3 d-flex justify-content-between">
    <div class="row">
        <!-- Campo de busca por título -->
        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-text">
                    <i class="fas fa-search"></i>
                </span>
                <input type="text" id="searchTitle" class="form-control" placeholder="Buscar por título">
            </div>
        </div>
        <!-- Campo de busca por autor -->
        <div class="col-md-6">
            <div class="input-group">
                <span class="input-group-text">
                    <i class="fas fa-user"></i>
                </span>
                <select id="searchAuthor" class="form-select">
                    <option value="">Todos os autores</option>
                    {% for author in authors %}
                        <option value="{{ author.id }}">{{ author }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
</div>

{% if books %}
<div class="row row-cols-1 row-cols-md-5 g-2 justify-content-center mt-3" id="bookGrid">
    {% for book in books %}
    <div class="col book-card" data-title="{{ book.title|lower }}" data-author="{{ book.author.id }}">
        <div class="card card-transition mx-auto mb-3 pt-3">            
            <a style="color: inherit" href="{% url 'books:book_details' book.id %}" title="{{ book.title }}"> 
                {% if book.cover_image %}
                    <img src="{{ book.cover_image.url }}" class="card-img-top" alt="Capa de {{ book.title }}">
                {% else %}
                    <img src="https://dummyimage.com/150x210/9e9e9e/030303.png&text=+SEM+CAPA" class="card-img-top" alt="Capa de {{ book.title }}">
                {% endif %}
            </a>
            <div class="card-body">
                <a style="color: inherit" href="{% url 'books:book_details' book.id %}"> 
                    <p class="card-title-text card-title padding-card book-title text-truncate" title="{{ book.title }}">{{ book }}</p>
                </a>
                <div>
                    <span class="card-bold margin-card-body">Author: </span>
                    <a style="color: inherit" href="#">
                        <span class="card-author-text card-text">{{ book.author }}</span>
                    </a>
                </div>
                <div>
                    <span class="card-bold margin-card-body">Publicação: </span>
                    <span class="card-text">{{ book.year }}</span>
                </div>
                <div>
                    <span class="card-bold margin-card-body">Gênero: </span>
                    <span class="card-text">{{ book.genre }}</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <div class="container d-flex justify-content-center align-items-center flex-column">
        <h5><i class="text-center">Ainda não existem livros cadastrados</i></h5>
        <img src="{% static 'icons/folder.png'%}" alt="Sem foto">
    </div>
{% endif %}

<script src="{% static 'js/filter_books.js' %}"></script>

{% endblock content %}