authors/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.author_register, name='authors'),
    path('edit/<int:author_id>/', views.edit_author, name='edit_author'),
    path('delete/', views.delete_author, name='delete_author'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.home, name='home'),
    path('book_register/', views.book_register, name='book_register'),
    path('book_details/<int:id>/', views.book_details, name='book_details'),
    path('book_edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('book_delete/<int:book_id>/', views.delete_book, name='book_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books_online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='authors/', blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

authors/forms.py
from django import forms
from .models import Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'photo']
        labels = {
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'photo': 'Foto do Autor'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sobrenome'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'})
        }
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if any(char.isdigit() for char in first_name):
            raise forms.ValidationError('O nome não pode conter números')
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if any(char.isdigit() for char in last_name):
            raise forms.ValidationError('O sobrenome não pode conter números')
        return last_name
    

authors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from .models import Author
from .forms import AuthorForm


def author_register(request):
    authors = Author.objects.all().order_by("first_name")
    
    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Autor(a) cadastrado(a) com sucesso!')
            return redirect("/authors/")
    else:
        form = AuthorForm()

    return render(request, "authors.html", {"form": form, "authors": authors})

def edit_author(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES, instance=author)
        if form.is_valid():
            if 'photo-clear' in request.POST:
                author.photo.delete()
            form.save()
            messages.success(request, 'Autor(a) editado(a) com sucesso!')
            return redirect('/authors/')
    else:
        form = AuthorForm(instance=author)
    return render(request, 'authors.html', {'form': form, 'author': author})

def delete_author(request):
    if request.method == 'POST':
        author_id = request.POST.get('author_id')
        author = get_object_or_404(Author, id=author_id)
        author.delete()
        messages.success(request, 'Autor(a) deletado(a) com sucesso!')
        return redirect(reverse('authors:authors'))

authors/templates/authors.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

<h2 class="text-center mb-3">Cadastre um novo autor</h2>

<form class="row g-3 justify-content-center mb-3" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-3">
        <div class="form-floating mb-3">
            {{ form.first_name }}
            <label for="{{ form.first_name.id_for_label }}">Nome</label>
            {% if form.first_name.errors %}
                <div class="text-danger">
                    {{ form.first_name.errors.0 }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-3">
        <div class="form-floating mb-3">
            {{ form.last_name }}
            <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
            {% if form.last_name.errors %}
                <div class="text-danger">
                    {{ form.last_name.errors.0 }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-3">
        <div class="form-control mb-3">
            {{ form.photo }}
        </div>
    </div>
    <div class="col-10 text-center">
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </div>
</form>

<hr class="mb-5">

{% if authors %}
<h3 class="text-center mb-5">Autores Cadastrados:</h3>
<div class="container d-flex justify-content-center table-responsive">
    <table class="table custom-table table-hover text-center">
        <thead class="custom-thead">
            <tr>
                <th scope="col" style="width: 150px;">Foto</th>
                <th scope="col" style="width: 400px;">Nome</th>
                <th scope="col" style="width: 150px;"></th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr class="align-middle">
                    {% if author.photo %}
                    <td><img src="{{ author.photo.url }}" alt="Foto do Autor" class="table-img"></td>
                    {% else %}
                    <td><img src="https://dummyimage.com/50x50/9e9e9e/030303.png&text=+SEM+FOTO" alt="Sem foto" class="table-img"></td>
                    {% endif %}
                    <td>{{ author }}</td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <button type="button" class="btn btn-sm btn-primary py-1 px-1 me-1 btn-edit" 
                                    data-author-id="{{ author.id }}" 
                                    data-author-first-name="{{ author.first_name }}" 
                                    data-author-last-name="{{ author.last_name }}" 
                                    data-author-photo-url="{% if author.photo %}{{ author.photo.url }}{% else %}https://dummyimage.com/150x150/9e9e9e/030303.png&text=+SEM+FOTO{% endif %}">
                                Editar
                            </button>
                            <button type="button" class="btn btn-sm btn-danger py-1 px-1 ms-1 btn-delete" 
                                    data-author-id="{{ author.id }}" 
                                    data-author-name="{{ author.first_name }} {{ author.last_name }}" 
                                    data-author-photo-url="{% if author.photo %}{{ author.photo.url }}{% else %}https://dummyimage.com/150x150/9e9e9e/030303.png&text=+SEM+FOTO{% endif %}">
                                Deletar
                            </button>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% else %}
<div class="container d-flex justify-content-center align-items-center flex-column">
    <h5><i class="text-center">Ainda não existem autores cadastrados</i></h5>
    <img src="{% static 'icons/folder.png'%}" alt="Sem foto">
</div>
{% endif %}

<!-- Modal para editar autor -->
{% include "edit_modal_author.html" %}

<!-- Modal para excluir autor-->
{% include "delete_modal_author.html" %}

<script src="{% static 'js/edit_author.js' %}"></script>
<script src="{% static 'js/delete_author.js' %}"></script>

{% endblock content %}

authors/templates/delete_modal_author.html
<div class="modal fade" id="deleteAuthorModal" tabindex="-1" aria-labelledby="deleteAuthorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteAuthorModalLabel">Deseja realmente deletar <i id="deleteAuthorName"></i>?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <img id="deleteAuthorPhoto" src="" alt="Foto do Autor" class="img-fluid mb-3" style="width: 250px; height: 250px;">
                
                <form id="deleteAuthorForm" method="post" action="{% url 'authors:delete_author' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="author_id" id="deleteAuthorId">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

authors/templates/edit_modal_author.html
<div class="modal fade" id="editAuthorModal" tabindex="-1" aria-labelledby="editAuthorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editAuthorModalLabel">Editar Autor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editAuthorForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3 text-center d-flex align-items-end gap-2" style="justify-content: center;">
                        <div style="position: relative; display: inline-block;">
                            <img id="authorPhoto" src="" alt="Foto do Autor" title="Alterar imagem" 
                                 class="img-thumbnail" style="width: 150px; height: 150px; cursor: pointer;">
                            <input type="file" class="form-control" id="editPhoto" name="photo" style="display: none;">
                            <input type="checkbox" name="photo-clear" id="photo-clear" style="display: none;">
                            <!-- Ícone da câmera -->
                            <i class="fas fa-camera position-absolute text-white bg-dark rounded-circle p-1"
                               style="bottom: 5px; left: 50%; transform: translateX(-50%); font-size: 16px; opacity: 0.7;">
                            </i>
                        </div>
                        
                        <button type="button" class="btn btn-danger btn-sm" id="deletePhotoButton" title="Deletar Foto">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </div>
                    
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="editFirstName" name="first_name" required>
                        <label for="editFirstName">Nome</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="editLastName" name="last_name" required>
                        <label for="editLastName">Sobrenome</label>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>